package az.millers.hcm.corehr.api.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

import az.millers.hcm.corehr.domain.EmploymentType;
import az.millers.hcm.corehr.domain.MaritalStatus;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Create / update payload for an employee. {@code employeeNo} is generated by the
 * system; {@code employmentStatus} starts at {@code ON_PROBATION} on creation
 * (PRD 8.1.4) and changes only through the status-transition endpoint.
 *
 * <p>M61: {@code maritalStatus}, {@code nationality}, {@code employmentType},
 * {@code ftePercent} are optional with sensible defaults — {@code PERMANENT} +
 * {@code ftePercent=100} preserves prior behaviour for callers that don't supply
 * them.
 */
public record EmployeeRequest(
        @NotBlank @Size(max = 100) String firstName,
        @NotBlank @Size(max = 100) String lastName,
        @Size(max = 100) String middleName,
        @Past LocalDate birthDate,
        @Size(max = 16) String gender,
        MaritalStatus maritalStatus,
        /** ISO 3166-1 alpha-2 country code (e.g. "AZ", "TR"). */
        @Pattern(regexp = "^[A-Z]{2}$", message = "nationality must be an ISO 3166-1 alpha-2 code")
        String nationality,
        @Size(max = 64) String nationalId,
        @Email @Size(max = 160) String email,
        @Size(max = 32) String phone,
        @NotNull LocalDate hireDate,
        @Size(max = 160) String departmentName,
        @Size(max = 160) String positionTitle,
        @Size(max = 64) String costCentre,
        UUID orgUnitId,
        UUID positionId,
        UUID managerId,
        /** M37 acting / delegate manager (PRD 9 / 14.9). Optional. */
        UUID delegateManagerId,
        LocalDate delegateFrom,
        LocalDate delegateTo,
        /** M61 / P1-09. Defaults to PERMANENT when null. */
        EmploymentType employmentType,
        /** M61 / P1-09. Defaults to 100.00 when null. */
        @DecimalMin(value = "0.01", message = "ftePercent must be > 0")
        @DecimalMax(value = "100.00", message = "ftePercent must be ≤ 100")
        BigDecimal ftePercent,
        /** M66 / P1-08. Null = use the default leave group. */
        UUID leaveGroupId,
        /** M75 / P2-19. Null = use the default payroll group. */
        UUID payrollGroupId,
        /** M75 / P2-21. Dotted-line manager — informational, not consumed by workflow engine. */
        UUID matrixManagerId,
        /** M78 / P2-15. Null defaults to true on create / preserves existing on update. */
        Boolean rehireEligible) {
}
