package az.millers.hcm.corehr.api.dto;

import java.time.LocalDate;
import java.util.UUID;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Size;

/**
 * Create / update payload for an employee. {@code employeeNo} is generated by the
 * system; {@code employmentStatus} starts at {@code ON_PROBATION} on creation
 * (PRD 8.1.4) and changes only through the status-transition endpoint.
 */
public record EmployeeRequest(
        @NotBlank @Size(max = 100) String firstName,
        @NotBlank @Size(max = 100) String lastName,
        @Size(max = 100) String middleName,
        @Past LocalDate birthDate,
        @Size(max = 16) String gender,
        @Size(max = 64) String nationalId,
        @Email @Size(max = 160) String email,
        @Size(max = 32) String phone,
        @NotNull LocalDate hireDate,
        @Size(max = 160) String departmentName,
        @Size(max = 160) String positionTitle,
        @Size(max = 64) String costCentre,
        UUID orgUnitId,
        UUID positionId,
        UUID managerId,
        /** M37 acting / delegate manager (PRD 9 / 14.9). Optional. */
        UUID delegateManagerId,
        LocalDate delegateFrom,
        LocalDate delegateTo) {
}
