package az.millers.hcm.corehr.api.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

import az.millers.hcm.corehr.domain.EmploymentType;
import az.millers.hcm.corehr.domain.MaritalStatus;
import az.millers.hcm.corehr.domain.EmployeeWorkType;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Create / update payload for an employee. {@code employeeNo} is generated by the
 * system; {@code employmentStatus} starts at {@code ON_PROBATION} on creation
 * (PRD 8.1.4) and changes only through the status-transition endpoint.
 *
 * <p>M61: {@code maritalStatus}, {@code nationality}, {@code employmentType},
 * {@code ftePercent} are optional with sensible defaults — {@code PERMANENT} +
 * {@code ftePercent=100} preserves prior behaviour for callers that don't supply
 * them.
 */
public record EmployeeRequest(
        @NotBlank @Size(max = 100) String firstName,
        @NotBlank @Size(max = 100) String lastName,
        @Size(max = 100) String middleName,
        @Past LocalDate birthDate,
        @Size(max = 16) String gender,
        MaritalStatus maritalStatus,
        /** ISO 3166-1 alpha-2 country code (e.g. "AZ", "TR"). */
        @Pattern(regexp = "^[A-Z]{2}$", message = "nationality must be an ISO 3166-1 alpha-2 code")
        String nationality,
        @Size(max = 64) String nationalId,
        /** VÖEN — individual taxpayer number (PRD §8.1.1). Encrypted at rest. */
        @Size(max = 64) String taxId,
        /** DSMF social-insurance ID (PRD §8.1.1). Encrypted at rest. */
        @Size(max = 64) String socialInsuranceId,
        @Email @Size(max = 160) String email,
        @Size(max = 32) String phone,
        @NotNull LocalDate hireDate,
        @Size(max = 160) String departmentName,
        @Size(max = 160) String positionTitle,
        @Size(max = 64) String costCentre,
        UUID orgUnitId,
        UUID positionId,
        UUID managerId,
        /** M141 — primary work location. */
        UUID workLocationId,
        /** M37 acting / delegate manager (PRD 9 / 14.9). Optional. */
        UUID delegateManagerId,
        LocalDate delegateFrom,
        LocalDate delegateTo,
        /** M61 / P1-09. Defaults to PERMANENT when null. */
        EmploymentType employmentType,
        /** M61 / P1-09. Defaults to 100.00 when null. */
        @DecimalMin(value = "0.01", message = "ftePercent must be > 0")
        @DecimalMax(value = "100.00", message = "ftePercent must be ≤ 100")
        BigDecimal ftePercent,
        /** M66 / P1-08. Null = use the default leave group. */
        UUID leaveGroupId,
        /** M75 / P2-19. Null = use the default payroll group. */
        UUID payrollGroupId,
        /** M75 / P2-21. Dotted-line manager — informational, not consumed by workflow engine. */
        UUID matrixManagerId,
        /** M146 / §9. Functional manager — informational, not consumed by workflow engine. */
        UUID functionalManagerId,
        /** M78 / P2-15. Null defaults to true on create / preserves existing on update. */
        Boolean rehireEligible,
        // ── M132 — Section 1 cosmetic completion ────────────────────────
        /** Nickname used in directory + printable badge. */

        /** City + country pair on HR cards. */
        /** ISO 3166-1 alpha-2, chosen from a list. */
        @Pattern(regexp = "^[A-Z]{2}$", message = "birthCountry must be an ISO 3166-1 alpha-2 code")
        String birthCountry,

        @Size(max = 120) String birthCity,

        @Size(max = 255) String birthAddress,
        // ── M133 — Section 3 contact completion ──────────────────────
        /** Personal alternative number — distinct from emergency-contact alt. */
        @Size(max = 32) String altPhone,
        /** Business email — typically @company.com. */
        @Email @Size(max = 160) String workEmail,
        /** Office main line. */
        @Size(max = 32) String workPhone,
        // ── M134 — Section 4 employment completion ──────────────────
        /** Configurable category (white/blue-collar, exec/mgr/IC, local/expat, …). */
        @Size(max = 60) String employeeCategory,
        /** Tenure anchor when set; otherwise {@code hireDate} is used. Cannot be in the future. */
        LocalDate seniorityDate,
        // ── M150 — workforce-register master data ───────────────────────
        /** Customer's GHRS / legacy-HRIS number. Unique per tenant when present. */
        @Size(max = 40) String externalHrId,
        /** Full legal name in local script — "SURNAME Name Patronymic oğlu". */
        @Size(max = 300) String fullNameLocal,
        /** Recruitment channel (agency, referral, direct, …). */
        @Size(max = 80) String sourceOfHire,
        /** Job title in the local language — used on contracts and orders. */
        @Size(max = 300) String positionTitleLocal,
        /** State occupational classifier entry ("Məşğulluq təsnifatı"). */
        @Size(max = 160) String occupationClassification,
        /** Internal grade bucket (Specialist / Manager / Worker / Director). */
        @Size(max = 60) String positionClassification,
        /** Onshore / offshore / quayside / hybrid. */
        EmployeeWorkType workType,
        /** Cost-bearing project label from the personnel register. */
        @Size(max = 200) String projectName,
        /** Total professional experience in years; feeds seniority leave brackets. */
        @DecimalMin(value = "0", message = "professionalExperienceYears must be ≥ 0")
        @DecimalMax(value = "70", message = "professionalExperienceYears must be ≤ 70")
        BigDecimal professionalExperienceYears,
        /** Signed-job-description tracking flag ("Provided", "Waiting from …"). */
        @Size(max = 120) String jobDescriptionStatus,
        /** Timesheet approver. Null = fall back to the line manager. */
        UUID timesheetApproverId,
        /** Expense approver. Null = fall back to the line manager. */
        UUID expenseApproverId,
        /** HR-side timesheet verifier, checked before payroll pickup. */
        UUID hrTimesheetVerifierId,
        /** Agreed work pattern as worded in the contract. */
        @Size(max = 200) String workScheduleText,
        /** Agreed daily working hours — e.g. "8:00 - 17:00". */
        @Size(max = 60) String workTimeText,
        /** Agreed unpaid break — e.g. "13:00 - 14:00". */
        @Size(max = 60) String lunchTimeText,
        /** Offshore rotation pattern when it differs — e.g. "12 hrs p/d". */
        @Size(max = 120) String offshoreWorkScheduleText,
        /** Summarized working-time accounting period (Art. 62). */
        @Size(max = 80) String summarizedPeriodMethod,

        // ── PRD §4 steps 4-5: contract and pay are captured during the hire ──
        // Optional so every existing caller (recruitment hire, bulk import)
        // keeps working; when present, EmployeeService opens the contract and
        // the first salary row in the same transaction as the employee, which
        // is what stops HR having to visit three screens to finish one hire.

        /** Contract start. Defaults to the hire date when a contract is opened. */
        LocalDate contractStartDate,

        /** Contract end. Null means indefinite (PRD §6). */
        LocalDate contractEndDate,

        /** Fixed-term / permanent. Defaults to the employee's employment type. */
        EmploymentType contractType,

        /** First monthly base salary. Writing it needs HR-admin rights (PRD §11). */
        @DecimalMin(value = "0.0", inclusive = false, message = "monthlyBaseSalary must be greater than zero")
        BigDecimal monthlyBaseSalary,

        /** When that salary takes effect. Defaults to the contract start. */
        LocalDate salaryEffectiveFrom) {
}
