-- V120 — PayrollRun run_type + final-settlement support (M180 / PRD §8.11.4)
--
-- Allows a FINAL_SETTLEMENT run to coexist with a REGULAR run in the same
-- period. Replaces the period-level unique constraint with a partial index
-- covering only REGULAR runs, and adds a termination_id FK column so the
-- run can be traced back to its originating termination request.

-- 1. Add run_type (REGULAR | FINAL_SETTLEMENT)
ALTER TABLE payroll.payroll_run
    ADD COLUMN IF NOT EXISTS run_type VARCHAR(30) NOT NULL DEFAULT 'REGULAR'
        CONSTRAINT payroll_run_type_ck CHECK (run_type IN ('REGULAR','FINAL_SETTLEMENT'));

-- 2. Link to the originating termination request (nullable — REGULAR runs omit it)
ALTER TABLE payroll.payroll_run
    ADD COLUMN IF NOT EXISTS termination_id UUID;

-- 3. Drop the old unconditional unique constraint (name auto-generated by PG)
DO $$
DECLARE
    con TEXT;
BEGIN
    SELECT constraint_name INTO con
    FROM information_schema.table_constraints
    WHERE table_schema = 'payroll'
      AND table_name   = 'payroll_run'
      AND constraint_type = 'UNIQUE'
      AND constraint_name LIKE '%period_year%period_month%jurisdiction%';
    IF con IS NOT NULL THEN
        EXECUTE 'ALTER TABLE payroll.payroll_run DROP CONSTRAINT ' || quote_ident(con);
    END IF;
END $$;

-- 4. Partial unique index — REGULAR runs remain unique per period+jurisdiction;
--    FINAL_SETTLEMENT runs are identified only by their unique run_no.
CREATE UNIQUE INDEX IF NOT EXISTS idx_payroll_run_period_regular
    ON payroll.payroll_run (period_year, period_month, jurisdiction)
    WHERE run_type = 'REGULAR';

-- 5. Index to quickly find all final-settlement runs for a given termination
CREATE INDEX IF NOT EXISTS idx_payroll_run_termination
    ON payroll.payroll_run (termination_id)
    WHERE termination_id IS NOT NULL;
