-- ----------------------------------------------------------------------------
-- M462 — HCM_30 Phase B.3: Loan Installment Schedule (computed at approval).
--
-- Equal installments, projected month dates, running balance. Generated by
-- LoanInstallmentService on approval. HR/Finance GET + ESS "my loan statement".
-- Regenerated on reschedule/settle (M463), never deleted (append/replace).
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS payroll.loan_installment_schedule (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               varchar(80)  NOT NULL DEFAULT 'default',
    loan_request_id         uuid         NOT NULL REFERENCES payroll.loan_request(id),
    payroll_loan_id         uuid,
    installment_number      int          NOT NULL,
    due_year                int          NOT NULL,
    due_month               int          NOT NULL,
    installment_amount      numeric(12,2) NOT NULL,
    principal_amount        numeric(12,2) NOT NULL,
    interest_amount         numeric(12,2) NOT NULL DEFAULT 0.00,
    remaining_balance       numeric(12,2) NOT NULL,
    paid_amount             numeric(12,2) NOT NULL DEFAULT 0.00,
    paid_at                 timestamptz,
    status                  varchar(20)  NOT NULL DEFAULT 'PENDING',
    created_at              timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT loan_installment_schedule_status_check
        CHECK (status IN ('PENDING', 'PAID', 'PARTIALLY_PAID', 'WAIVED'))
);

CREATE INDEX IF NOT EXISTS loan_installment_schedule_tenant_idx ON payroll.loan_installment_schedule (tenant_id);
CREATE INDEX IF NOT EXISTS loan_installment_schedule_loan_request_idx ON payroll.loan_installment_schedule (loan_request_id);
CREATE INDEX IF NOT EXISTS loan_installment_schedule_payroll_loan_idx ON payroll.loan_installment_schedule (payroll_loan_id);
CREATE INDEX IF NOT EXISTS loan_installment_schedule_due_idx ON payroll.loan_installment_schedule (due_year, due_month);

COMMENT ON TABLE payroll.loan_installment_schedule IS
    'M462 — Loan installment schedule computed at approval. Equal installments, projected dates, running balance.';
